export enum LOG_MOVEMENTS {
  LOGIN = 'INICIO DE SESIÓN',
  LOGOUT = 'CIERRE DE SESIÓN',
  EDIT = 'EDITAR',
  NEW_REGISTER = 'CREAR',
  INACTIVE = 'ELIMINAR',
  REACTIVATE = 'ACTIVAR',
  DELETE = 'ELIMINAR',
  CHANGE_PASSWORD = 'CAMBIO CONTRASEÑA',
  ADD_ROLES_TO_USER = 'ASIGNAR ROL A USUARIO',
  REMOVE_ROLES_FROM_USER = 'REMOVER ROL A USUARIO',
  ADD_PERMISSIONS_TO_ROLE = 'ASIGNAR PERMISOS A ROL',
}
