export enum LOG_MOVEMENTS {
  LOGIN = 1,
  LOGOUT = 2,
  EDIT = 3,
  NEW_REGISTER = 4,
  INACTIVE = 5,
  REACTIVATE = 6,
  DELETE = 7,
  CHANGE_PASSWORD = 8,
  ADD_ROLES_TO_USER = 9,
  REMOVE_ROLES_FROM_USER = 10,
  ADD_PERMISSIONS_TO_ROLE = 11,
}
